package Zaur_OOP.podpaket_lesson27_exceptions_and_mistakes.exception_classes;public class Test2 {
}
