package JavaRushTaskSt.Zadachi_15.LV.Correct_operation_of_the_program.Exceptions.Throwing_exceptions;

import java.io.FileInputStream;

//3. Ключевое слово finally
/*
Еще один важный момент. Иногда программисту нужно сделать некоторые действия независимо от того,
было исключение в коде или нет.
Например, в коде мы открыли файл на запись, а открытый файл нужно обязательно закрыть вызовом метода close().
* */
public class Test3 {
    public static void main(String[] args) {
//        FileInputStream source = null;
//        try
//        {
//            source = new FileInputStream("c:\\note.txt");
//            source.read();
//        }
//        catch(Exception except)
//        {
//            System.out.println("Перехватили исключение");
//            throw except;
//        }
//        finally
//        {
//            if (source != null)
//                source.close();
//        }
    }
}
